version: '3'
services:
  alb:
    container_name: alb
    build: ./ALB
    ports:
        - "80:80"
    networks:
      - mynet
    depends_on:
      - app
  app:
  container_name: app
    build: .
    networks:
      - mynet
    depends_on:
      my_data:
        condition: service_healthy 

  my_data:
    container_name: my_data
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatDB
    ports:
      - "3306:3306"
    volumes:
      - my_data:/var/lib/mysql
    networks:
      - mynet
    healthcheck: # check the healthiness with the following configuration
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=root', '--password=root']
      interval: 3s
      timeout: 3s
      retries: 15 
 
networks:
  mynet:
    

volumes:
  my_data:
